# Generated by Django 4.1.4 on 2022-12-31 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='server',
        ),
        migrations.DeleteModel(
            name='Chats',
        ),
        migrations.DeleteModel(
            name='ServerList',
        ),
        migrations.DeleteModel(
            name='UserList',
        ),
    ]
