# Generated by Django 4.1.4 on 2022-12-31 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatroom_app', '0002_remove_userlist_server_delete_chats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerList',
            fields=[
                ('server', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('lockStatus', models.BooleanField()),
                ('lastUpdate', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatroom_app.serverlist')),
            ],
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('chatID', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16)),
                ('message', models.CharField(max_length=256)),
                ('time', models.TimeField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatroom_app.serverlist')),
            ],
        ),
    ]
