# Generated by Django 4.1.4 on 2023-01-11 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
