# Generated by Django 4.1.4 on 2023-01-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom_app', '0005_alter_chats_time_alter_serverlist_lastupdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverlist',
            name='password',
            field=models.CharField(default='none', max_length=16),
            preserve_default=False,
        ),
    ]
